// <auto-generated />
using Aether.Repositories.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aether.Repositories.Migrations
{
    [DbContext(typeof(AetherContext))]
    [Migration("20250515202325_create_air_quality_readings")]
    partial class create_air_quality_readings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aether.Core.Entities.AirQualityReadingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Ammonia")
                        .HasColumnType("double precision")
                        .HasColumnName("ammonia");

                    b.Property<double>("CarbonMonoxide")
                        .HasColumnType("double precision")
                        .HasColumnName("carbon_monoxide");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<double>("NitrogenDioxide")
                        .HasColumnType("double precision")
                        .HasColumnName("nitrogen_dioxide");

                    b.Property<double>("NitrogenOxide")
                        .HasColumnType("double precision")
                        .HasColumnName("nitrogen_oxide");

                    b.Property<double>("Ozone")
                        .HasColumnType("double precision")
                        .HasColumnName("ozone");

                    b.Property<double>("ParticulateMatter10")
                        .HasColumnType("double precision")
                        .HasColumnName("particulate_matter10");

                    b.Property<double>("ParticulateMatter2_5")
                        .HasColumnType("double precision")
                        .HasColumnName("particulate_matter2_5");

                    b.Property<double>("SulfurDioxide")
                        .HasColumnType("double precision")
                        .HasColumnName("sulfur_dioxide");

                    b.HasKey("Id")
                        .HasName("pk_air_quality_readings");

                    b.HasIndex("LocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_air_quality_readings_location_id");

                    b.ToTable("air_quality_readings", (string)null);
                });

            modelBuilder.Entity("Aether.Core.Entities.LocationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("Aether.Core.Entities.AirQualityReadingEntity", b =>
                {
                    b.HasOne("Aether.Core.Entities.LocationEntity", "Location")
                        .WithOne("AirQualityReading")
                        .HasForeignKey("Aether.Core.Entities.AirQualityReadingEntity", "LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_air_quality_readings_locations_location_id");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Aether.Core.Entities.LocationEntity", b =>
                {
                    b.Navigation("AirQualityReading");
                });
#pragma warning restore 612, 618
        }
    }
}
